const actionTypes = {
  INPUT_SEARCH_NAME: "INPUT_SEARCH_NAME",
  INPUT_SEARCH_RATE: "INPUT_SEARCH_RATE",
  SEARCH_MOVIE: "SEARCH_MOVIE",
  ADD_MOVIE: "ADD_MOVIE",
  REMOVE_MOVIE: "REMOVE_MOVIE",
  EDIT_MOVIE: "EDIT_MOVIE",
  UPDATE_MOVIE: "UPDATE_MOVIE",
};
export default actionTypes;
